%% Connection to Lasers %%
% The code segment below establishes serial communication 
% with the laser.

function [hObject, eventdata, handles] = connect2lasers(hObject, eventdata, handles)
disp(['Connecting to lasers on COM ', num2str(handles.laserPortNum)]);
%handles.laserConnection = serial(['COM', num2str(handles.laserPortNum)]);
handles.laserConnection = serialport(['COM', num2str(handles.laserPortNum)], 9600);
set(handles.laserConnection,...
    'baudrate', 9600,...
    'parity', 'none',...
    'databits', 8,...
    'stopbits', 1,...
    'terminator', 13,...
    'bytesAvailableFcnMode', 'byte',...
    'bytesAvailableFcnCount', 2,...
    'flowControl', 'none');
fopen(handles.laserConnection);


% inititalization commands
initCmd1 = sscanf('57 02 FF 50', '%2X');
initCmd2 = sscanf('57 03 AB 50', '%2X');
fwrite(handles.laserConnection, initCmd1, 'uint8');
fwrite(handles.laserConnection, initCmd2, 'uint8');
end