function [hObject, eventdata, handles] = connect2stage(hObject, eventdata, handles)
disp(['Connecting to stage on COM ', num2str(handles.stagePortNum)]);
handles.stageConnection = serial(['COM', num2str(handles.stagePortNum)]);
set(handles.stageConnection,...
    'baudrate', 115200,...
    'parity', 'none',...
    'databits', 8,...
    'stopbits', 1,...
    'requesttosend', 'on',...
    'dataterminalready', 'on',...
    'timeout', 1,...
    'outputbuffersize', 512,...
    'inputbuffersize', 1024,...
    'bytesAvailableFcnMode', 'byte',...
    'bytesAvailableFcnCount', 3,...
    'terminator', '',...
    'flowControl', 'none',...
    'recordName', 'myRecord.txt',...
    'recordDetail', 'verbose');
fopen(handles.stageConnection);
guidata(hObject, handles);
fwrite(handles.stageConnection, [char(255) char(66)]); % low level commands mode
guidata(hObject, handles);
end


